# Site settings
title: Slice of Pi
email: miriam.angell.cox@gmail.com
description: > # this means to ignore newlines until "baseurl
	Hey there! I'm a computing student at K-State who loves to solve problems 
	code, toy with microcontrollers, garden, eat delicious snacks, and geek out
	about nerd culture!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miriamcox.net" # the base hostname & protocol for your site
twitter_username: marzipanicked
github_username:  miriamcox

# Build settings
markdown: kramdown

paginate: 4

author: Miriam Cox

gems: [jekyll-paginate]
