# Permalinks
permalink:           pretty

# Setup
title:               Pixel Pie
tagline:             'Food for thought.'
description:         'This corner of the cloud belongs to Miriam Cox, a cybersecurity amateur, pop fantasy nerd, and aspiring foodie.'
url:                 http://miriamcox.net
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]

# About/contact
author:
  name:              Miriam Cox
  url:               http://miriamcox.net
  email:             miriam.angell.cox@gmail.com
  codepen:           http://codepen.io/miriamcox/
  github:            https://github.com/miriamcox
  twitter:           https://twitter.com/mdo
  facebook:          https://www.facebook.com/miriamangell
  linkedin:          https://www.linkedin.com/in/miriam-cox-a0051876
  steam:             http://steamcommunity.com/id/marzipanic/

# Custom vars
version:             1.0.0
